# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Darwinist
email: info@darwinist.io
description: >- # this means to ignore newlines until "baseurl:"
  Strategic healthcare technology insights and digital transformation resources.
  Exploring the evolution of medical AI, data standards, and clinical innovation
  to drive better patient outcomes and operational efficiency.
baseurl: "" # Leave empty if using custom domain
url: "https://darwinist-io.github.io" # Your custom domain or https://username.github.io

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

collections:
  docs:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Pagination
paginate: 5
paginate_path: "/blog/page:num/"

# SEO and metadata
author: "Darwinist Team"
twitter:
  username: darwinist_io
social:
  name: Darwinist
  links:
    - https://twitter.com/darwinist_io

# Defaults
defaults:
  - scope:
      path: ""
      type: "docs"
    values:
      layout: "document"
      author: "Darwinist Team"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Darwinist Team"

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE


  # Include directories for GitHub Pages
include:
  - blog
  - team
  - partners


# Google Analytics
google_analytics: G-T4TN8DVP2H